apiVersion: apps/v1
kind: Deployment
metadata:
  name: WorkLoadName
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: WorkLoadName
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: WorkLoadName
    spec:
      containers:
      - image: "192.168.203.40:80/library/helloworld:tags"
        imagePullPolicy: IfNotPresent
        name: WorkLoadName
        ports:
          - containerPort: 8080
            name: tcp-8080
            protocol: TCP
        securityContext:
          privileged: false  
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: svc-WorkLoadName
  namespace: default
spec:
  ports:
  - name: tcp-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    k8s-app: WorkLoadName
