apiVersion: apps/v1
kind: Deployment
metadata:
  name: WorkLoadName
  namespace: NameSpace
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: WorkLoadName
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: WorkLoadName
    spec:
      containers:
      - image: "Iamge"
        imagePullPolicy: IfNotPresent
        name: WorkLoadName
        ports:
          - containerPort: AppPort
            name: tcp-AppPort
            protocol: TCP
        securityContext:
          privileged: false  
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: svc-WorkLoadName
  namespace: NameSpace
spec:
  ports:
  - name: tcp-AppPort
    port: AppPort
    protocol: TCP
    targetPort: AppPort
  selector:
    k8s-app: WorkLoadName
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-WorkLoadName
  #annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /$2
  namespace: NameSpace
spec:
  ingressClassName: nginx
  rules:
  - host:  # Replace with your domain or IP
    http:
      paths:
      #- path: /nginx(/|$)(.*)
      - path: /Path
        pathType: Prefix
        backend:
          service:
            name: svc-WorkLoadName
            port:
              number: AppPort
