apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/captains/heptio-images-ks-guestbook-demo:0.2
        name: helloworld
        ports:
        - containerPort: 8080
